#!/data/data/com.termux/files/usr/bin/bash
#
# export.sh — Report export module
#
# Exports device reports in multiple formats:
#   - Markdown (.md)
#   - JSON (.json)
#   - CSV (.csv)
#   - HTML (.html)
#   - PDF (.pdf — via pandoc if available)
#   - ZIP archive (.zip) bundling all reports + logs
#
# Part of the Android Toolkit.

EXPORT_DIR="${ANDROID_TOOLKIT_ROOT_DIR}/exports"

##############################################
# Ensure export directory exists.
##############################################
export_init() {
    mkdir -p "$EXPORT_DIR"
}

##############################################
# Collect all report data into associative arrays.
##############################################
_export_collect_data() {
    local -n _data=$1

    # Device info
    _data["device_manufacturer"]="${CAP_MANUFACTURER:-unknown}"
    _data["device_model"]="${CAP_MODEL:-unknown}"
    _data["android_version"]="${CAP_ANDROID_VERSION:-unknown}"
    _data["android_sdk"]="${CAP_ANDROID_SDK:-unknown}"
    _data["one_ui_version"]="${CAP_ONE_UI_VERSION:-unknown}"
    _data["kernel"]="${CAP_KERNEL:-unknown}"
    _data["abi"]="${CAP_ABI:-unknown}"
    _data["backend"]="${ANDROID_TOOLKIT_BACKEND:-unknown}"
    _data["oem"]="${OEM_LOADED:-generic}"
    _data["version"]="${ANDROID_TOOLKIT_VERSION}"
    _data["date"]="$(date -Iseconds 2>/dev/null || date '+%Y-%m-%dT%H:%M:%S%z')"

    # Capabilities summary
    _data["capabilities"]="$(cap_list 2>/dev/null | paste -sd ';' || echo 'none')"

    # Log file
    _data["log_file"]="${LOG_FILE:-unknown}"
}

##############################################
# Export report in Markdown format.
# Arguments:
#   $1: output file path (optional)
##############################################
export_markdown() {
    local output="${1:-${EXPORT_DIR}/report.md}"
    export_init

    declare -A data
    _export_collect_data data

    cat > "$output" << EOF
# Android Toolkit Report

**Generated:** ${data[date]}  
**Toolkit Version:** ${data[version]}  
**Device:** ${data[device_manufacturer]} ${data[device_model]}  
**Android:** ${data[android_version]} (SDK ${data[android_sdk]})  
**Kernel:** ${data[kernel]}  
**OEM:** ${data[oem]}  
**Backend:** ${data[backend]}

## Device Information

| Property | Value |
|----------|-------|
| Manufacturer | ${data[device_manufacturer]} |
| Model | ${data[device_model]} |
| Android Version | ${data[android_version]} |
| SDK Level | ${data[android_sdk]} |
| One UI Version | ${data[one_ui_version]} |
| Kernel | ${data[kernel]} |
| ABI | ${data[abi]} |

## Diagnostics

Full diagnostics output available via \`toolkit.sh --doctor\`.

## Logs

Main log: \`${data[log_file]}\`

---

*Report generated by Android Toolkit v${data[version]}*
EOF

    log_success "Markdown report: $output"
    echo "$output"
}

##############################################
# Export report in JSON format.
# Arguments:
#   $1: output file path (optional)
##############################################
export_json() {
    local output="${1:-${EXPORT_DIR}/report.json}"
    export_init

    declare -A data
    _export_collect_data data

    if command -v jq &>/dev/null; then
        jq -n \
            --arg date "${data[date]}" \
            --arg version "${data[version]}" \
            --arg man "${data[device_manufacturer]}" \
            --arg model "${data[device_model]}" \
            --arg av "${data[android_version]}" \
            --arg sdk "${data[android_sdk]}" \
            --arg oui "${data[one_ui_version]}" \
            --arg kernel "${data[kernel]}" \
            --arg abi "${data[abi]}" \
            --arg backend "${data[backend]}" \
            --arg oem "${data[oem]}" \
            --arg caps "${data[capabilities]}" \
            --arg log "${data[log_file]}" \
            '{
                report: {
                    generated: $date,
                    toolkit_version: $version,
                    device: {
                        manufacturer: $man,
                        model: $model,
                        android_version: $av,
                        android_sdk: $sdk,
                        one_ui_version: $oui,
                        kernel: $kernel,
                        abi: $abi
                    },
                    runtime: {
                        backend: $backend,
                        oem: $oem
                    },
                    capabilities: $caps | split(";"),
                    log_file: $log
                }
            }' > "$output" 2>/dev/null
    else
        # Fallback without jq
        cat > "$output" << JSONEOF
{
  "report": {
    "generated": "${data[date]}",
    "toolkit_version": "${data[version]}",
    "device": {
      "manufacturer": "${data[device_manufacturer]}",
      "model": "${data[device_model]}",
      "android_version": "${data[android_version]}",
      "android_sdk": "${data[android_sdk]}",
      "one_ui_version": "${data[one_ui_version]}",
      "kernel": "${data[kernel]}",
      "abi": "${data[abi]}"
    },
    "runtime": {
      "backend": "${data[backend]}",
      "oem": "${data[oem]}"
    },
    "log_file": "${data[log_file]}"
  }
}
JSONEOF
    fi

    log_success "JSON report: $output"
    echo "$output"
}

##############################################
# Export report in CSV format.
# Arguments:
#   $1: output file path (optional)
##############################################
export_csv() {
    local output="${1:-${EXPORT_DIR}/report.csv}"
    export_init

    declare -A data
    _export_collect_data data

    {
        echo "Section,Property,Value"
        echo "Device,Manufacturer,${data[device_manufacturer]}"
        echo "Device,Model,${data[device_model]}"
        echo "Device,Android Version,${data[android_version]}"
        echo "Device,SDK Level,${data[android_sdk]}"
        echo "Device,One UI Version,${data[one_ui_version]}"
        echo "Device,Kernel,${data[kernel]}"
        echo "Device,ABI,${data[abi]}"
        echo "Runtime,Backend,${data[backend]}"
        echo "Runtime,OEM,${data[oem]}"
        echo "Runtime,Log File,${data[log_file]}"
    } > "$output"

    log_success "CSV report: $output"
    echo "$output"
}

##############################################
# Export report in HTML format.
# Arguments:
#   $1: output file path (optional)
##############################################
export_html() {
    local output="${1:-${EXPORT_DIR}/report.html}"
    export_init

    declare -A data
    _export_collect_data data

    cat > "$output" << HTMLEOF
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Android Toolkit Report</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, sans-serif; max-width: 800px; margin: 0 auto; padding: 2em; background: #0d1117; color: #c9d1d9; }
  h1 { color: #58a6ff; border-bottom: 1px solid #30363d; padding-bottom: 0.5em; }
  h2 { color: #58a6ff; }
  table { border-collapse: collapse; width: 100%; margin: 1em 0; }
  th, td { text-align: left; padding: 0.5em; border-bottom: 1px solid #30363d; }
  th { color: #8b949e; }
  .meta { color: #8b949e; font-size: 0.9em; }
  .footer { margin-top: 2em; color: #8b949e; font-size: 0.8em; border-top: 1px solid #30363d; padding-top: 1em; }
</style>
</head>
<body>
<h1>Android Toolkit Report</h1>
<p class="meta">Generated: ${data[date]} &middot; v${data[version]}</p>

<h2>Device Information</h2>
<table>
  <tr><th>Property</th><th>Value</th></tr>
  <tr><td>Manufacturer</td><td>${data[device_manufacturer]}</td></tr>
  <tr><td>Model</td><td>${data[device_model]}</td></tr>
  <tr><td>Android Version</td><td>${data[android_version]}</td></tr>
  <tr><td>SDK Level</td><td>${data[android_sdk]}</td></tr>
  <tr><td>One UI Version</td><td>${data[one_ui_version]}</td></tr>
  <tr><td>Kernel</td><td>${data[kernel]}</td></tr>
  <tr><td>ABI</td><td>${data[abi]}</td></tr>
</table>

<h2>Runtime</h2>
<table>
  <tr><th>Property</th><th>Value</th></tr>
  <tr><td>Backend</td><td>${data[backend]}</td></tr>
  <tr><td>OEM</td><td>${data[oem]}</td></tr>
  <tr><td>Log File</td><td><code>${data[log_file]}</code></td></tr>
</table>

<div class="footer">
  Generated by Android Toolkit v${data[version]} &mdash; ${data[date]}
</div>
</body>
</html>
HTMLEOF

    log_success "HTML report: $output"
    echo "$output"
}

##############################################
# Export report as PDF (via pandoc if available).
# Arguments:
#   $1: output file path (optional)
##############################################
export_pdf() {
    local output="${1:-${EXPORT_DIR}/report.pdf}"

    if command -v pandoc &>/dev/null; then
        local md_file
        md_file="$(export_markdown "${EXPORT_DIR}/.tmp_report.md")"
        if pandoc "$md_file" -o "$output" 2>/dev/null; then
            rm -f "$md_file"
            log_success "PDF report: $output"
            echo "$output"
        else
            rm -f "$md_file"
            log_error "PDF generation failed (pandoc error)"
            return 1
        fi
    else
        log_warning "pandoc not available — cannot generate PDF"
        log_info "Install pandoc: pkg install pandoc"
        log_info "Falling back to HTML..."
        export_html "$output"  # Return HTML path as fallback
    fi
}

##############################################
# Create a ZIP archive with all reports and logs.
# Arguments:
#   $1: output file path (optional)
##############################################
export_zip() {
    local timestamp
    timestamp="$(date '+%Y%m%d_%H%M%S')"
    local output="${1:-${EXPORT_DIR}/android-toolkit-report-${timestamp}.zip}"

    export_init

    # Generate all report formats
    local md_file json_file csv_file html_file
    md_file="$(export_markdown "${EXPORT_DIR}/.export_report.md")"
    json_file="$(export_json "${EXPORT_DIR}/.export_report.json")"
    csv_file="$(export_csv "${EXPORT_DIR}/.export_report.csv")"
    html_file="$(export_html "${EXPORT_DIR}/.export_report.html")"

    # Collect logs
    local logs_to_include=()
    if [[ -n "$LOG_FILE" && -f "$LOG_FILE" ]]; then
        logs_to_include+=("$LOG_FILE")
    fi

    if command -v zip &>/dev/null; then
        (
            cd "$EXPORT_DIR" || return 1
            zip -j "$output" \
                ".export_report.md" \
                ".export_report.json" \
                ".export_report.csv" \
                ".export_report.html" \
                "${logs_to_include[@]}" \
                2>/dev/null
        )

        # Cleanup temp files
        rm -f "$md_file" "$json_file" "$csv_file" "$html_file"

        log_success "ZIP archive: $output"
        echo "$output"
    else
        log_warning "zip not available — cannot create archive"
        log_info "Install zip: pkg install zip"
        echo "$md_file"  # Return MD path as fallback
    fi
}

##############################################
# Main export entry point.
# Arguments:
#   $1: format (md|json|csv|html|pdf|zip)
##############################################
export_report() {
    local format="${1:-md}"

    log_section "Export Report"

    case "$format" in
        md|markdown)    export_markdown ;;
        json)           export_json ;;
        csv)            export_csv ;;
        html)           export_html ;;
        pdf)            export_pdf ;;
        zip|archive)    export_zip ;;
        *)
            log_error "Unknown format: $format"
            log_info "Supported formats: md, json, csv, html, pdf, zip"
            return 1
            ;;
    esac

    log_show_file
}
