#!/data/data/com.termux/files/usr/bin/bash
#
# 20-reporting.sh — Example: Custom Reporting Plugin
#
# Demonstrates how to generate custom device reports using toolkit APIs.
# Plugin SDK v3.0 feature.
#
# Usage:
#   toolkit.sh --plugin reporting-example
#
# This plugin collects device information and outputs a formatted report.
# It demonstrates:
#   - Using api_* functions for safe backend access
#   - Structured output formatting
#   - Device property collection
#
# Part of the Android Toolkit — Plugin Examples.
# Licensed under MIT.

plugin_name="Reporting Example"
plugin_version="1.0.0"
plugin_supported_oems="all"
plugin_supported_android="33 34 35 36"

##############################################
# Register plugin.
##############################################
plugin_register() {
    log_debug "Reporting example registered"
}

##############################################
# Collect and display a custom device report.
#
# Demonstrates safe API usage patterns.
##############################################
plugin_run() {
    echo "══════════════════════════════════════════"
    echo "  Custom Device Report (Plugin Example)"
    echo "══════════════════════════════════════════"
    echo ""

    # Use api_* functions where available (safe, stable API)
    local manufacturer model android_ver sdk
    manufacturer="$(api_device_manufacturer 2>/dev/null || echo "unknown")"
    model="$(api_device_model 2>/dev/null || echo "unknown")"
    android_ver="$(api_android_version 2>/dev/null || echo "unknown")"
    sdk="$(api_android_sdk 2>/dev/null || echo "0")"

    echo "  Device:        ${manufacturer} ${model}"
    echo "  Android:       ${android_ver} (SDK ${sdk})"

    # Use backend directly for specific queries
    local battery_level
    battery_level="$(backend_getprop "persist.sys.battery" 2>/dev/null || echo "unknown")"
    echo "  Battery prop:  ${battery_level}"

    # Use the settings database
    local airplane_mode
    airplane_mode="$(backend_settings_get global airplane_mode_on 2>/dev/null || echo "unknown")"
    echo "  Airplane mode: ${airplane_mode}"

    # Rollback integration — record this report generation
    if declare -f rollback_begin &>/dev/null; then
        echo ""
        echo "  Rollback system: available"
    fi

    echo ""
    echo "══════════════════════════════════════════"
    echo "  Report generated by ${plugin_name} v${plugin_version}"
    echo "══════════════════════════════════════════"

    return 0
}

##############################################
# Cleanup.
##############################################
plugin_cleanup() {
    log_trace "Reporting example cleaned up"
}
